# Creating a logistic regression to predict absenteeism

### Import the relevant libraries

In [1]:
import numpy as np
import pandas as pd

 ## Load the data

In [2]:
data_preprocessed = pd.read_csv(r'D:\data for data S\Absenteeism_preprocessed.csv')
data_preprocessed.head(10)

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pet,Absenteeism Time in Hours
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2
5,0,0,0,1,10,2,179,51,38,239.554,31,0,0,0,2
6,0,0,0,1,7,4,361,52,28,239.554,27,0,1,4,8
7,0,0,0,1,7,4,260,50,36,239.554,23,0,4,0,4
8,0,0,1,0,6,6,155,12,34,239.554,25,0,2,0,40
9,0,0,0,1,7,0,235,11,37,239.554,29,1,1,1,8

## Create the targets

In [3]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [4]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median()
                   , 1,0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0])

In [5]:
data_preprocessed['Excessive Absenteeism'] = targets
data_preprocessed

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pet,Absenteeism Time in Hours,Excessive Absenteeism
0,0,0,0,1,7,1,289,36,33,239.554,30,0,2,1,4,1
1,0,0,0,0,7,1,118,13,50,239.554,31,0,1,0,0,0
2,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,2,0
3,1,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4,1
4,0,0,0,1,7,3,289,36,33,239.554,30,0,2,1,2,0
5,0,0,0,1,10,2,179,51,38,239.554,31,0,0,0,2,0
6,0,0,0,1,7,4,361,52,28,239.554,27,0,1,4,8,1
7,0,0,0,1,7,4,260,50,36,239.554,23,0,4,0,4,1
8,0,0,1,0,6,6,155,12,34,239.554,25,0,2,0,40,1
9,0,0,0,1,7,0,235,11,37,239.554,29,1,1,1,8,1
10,1,0,0,0,7,0,260,50,36,239.554,23,0,4,0,8,1
11,1,0,0,0,7,1,260,50,36,239.554,23,0,4,0,8,1
12,1,0,0,0,7,2,260,50,36,239.554,23,0,4,0,8,1
13,1,0,0,0,7,2,179,51,38,239.554,31,0,0,0,1,0
14,0,0,0,1,7,2,179,51,38,239.554,31,0,0,0,4,1
15,1,0,0,0,7,4,246,25,41,239.554,23,0,0,0,8,1
16,0,0,0,1,7,4,179,51,38,239.554,31,0,0,0,2,0
17,0,0,1,0,7,0,179,51,38,239.554,31,0,0,0,8,1
18,1,0,0,0,7,3,189,29,33,239.554,25,0,2,2,8,1
19,0,0,0,1,5,4,248,25,47,205.917,32,0,2,1,2,0
20,1,0,0,0,12,1,330,16,28,205.917,25,1,0,0,8,1
21,1,0,0,0,3,6,179,51,38,205.917,31,0,0,0,1,0
22,1,0,0,0,10,3,361,52,28,205.917,27,0,1,4,40,1
23,0,0,0,1,8,4,260,50,36,205.917,23,0,4,0,4,1
24,0,0,1,0,8,0,289,36,33,205.917,30,0,2,1,8,1
25,0,0,0,1,8,0,361,52,28,205.917,27,0,1,4,7,1
26,0,0,0,1,4,2,289,36,33,205.917,30,0,2,1,1,0
27,0,0,0,1,12,1,157,27,29,205.917,22,0,0,0,4,1
28,0,0,1,0,8,2,289,36,33,205.917,30,0,2,1,8,1
29,0,0,0,1,8,4,179,51,38,205.917,31,0,0,0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,1,4,1,155,12,34,246.288,25,0,2,0,4,1
671,0,0,1,0,4,3,225,26,28,246.288,24,0,1,2,8,1
672,1,0,0,0,4,3,118,13,50,246.288,31,0,1,0,2,0
673,0,0,0,1,4,4,179,26,30,246.288,19,1,0,0,2,0
674,0,0,0,1,7,3,235,11,37,237.656,29,1,1,1,8,1
675,0,0,1,0,9,2,225,15,41,237.656,28,1,2,2,3,0
676,0,0,0,1,9,2,235,16,32,237.656,25,1,0,0,2,0
677,1,0,0,0,9,2,118,10,37,237.656,28,0,0,0,3,0
678,0,0,0,1,9,2,235,20,43,237.656,38,0,1,0,8,1
679,1,0,0,0,10,4,179,26,30,237.656,19,1,0,0,1,0
680,0,0,0,1,10,4,291,31,40,237.656,25,0,1,1,2,0
681,1,0,0,0,10,4,225,15,41,237.656,28,1,2,2,8,1
682,0,0,1,0,11,0,300,26,43,237.656,25,0,2,1,64,1
683,0,0,0,1,11,0,225,15,41,237.656,28,1,2,2,8,1
684,0,0,0,1,11,0,179,26,30,237.656,19,1,0,0,2,0
685,0,0,0,1,5,0,118,13,50,237.656,31,0,1,0,2,0
686,1,0,0,0,5,1,118,13,50,237.656,31,0,1,0,3,0
687,0,0,0,1,5,1,118,10,37,237.656,28,0,0,0,1,0
688,0,0,0,0,5,1,118,13,50,237.656,31,0,1,0,0,0
689,0,0,0,1,5,2,179,26,30,237.656,19,1,0,0,2,0
690,0,0,0,0,5,2,378,49,36,237.656,21,0,2,4,0,0
691,0,1,0,0,5,4,179,22,40,237.656,22,1,2,0,1,0
692,1,0,0,0,5,0,155,12,34,237.656,25,0,2,0,48,1
693,1,0,0,0,5,0,235,16,32,237.656,25,1,0,0,8,1
694,0,0,0,1,5,2,291,31,40,237.656,25,0,1,1,8,1
695,1,0,0,0,5,2,179,22,40,237.656,22,1,2,0,8,1
696,1,0,0,0,5,2,225,26,28,237.656,24,0,1,2,3,0
697,1,0,0,0,5,3,330,16,28,237.656,25,1,0,0,8,1
698,0,0,0,1,5,3,235,16,32,237.656,25,1,0,0,2,0
699,0,0,0,1,5,3,291,31,40,237.656,25,0,1,1,2,0

## A comment on the targets

In [6]:
targets.sum()/ targets.shape[0]

0.45571428571428574

## Create the chechpoint

In [74]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours',
                                           'Day of the Week','Daily Work Load Average','Distance to Work'],axis=1)
data_with_targets.head()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pet,Excessive Absenteeism
0,0,0,0,1,7,289,33,30,0,2,1,1
1,0,0,0,0,7,118,50,31,0,1,0,0
2,0,0,0,1,7,179,38,31,0,0,0,0
3,1,0,0,0,7,279,39,24,0,2,0,1
4,0,0,0,1,7,289,33,30,0,2,1,0

## Select the Inputs for the regression

In [75]:
data_with_targets.shape

(700, 12)

In [78]:
data_with_targets.iloc[:,:11]

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pet
0,0,0,0,1,7,289,33,30,0,2,1
1,0,0,0,0,7,118,50,31,0,1,0
2,0,0,0,1,7,179,38,31,0,0,0
3,1,0,0,0,7,279,39,24,0,2,0
4,0,0,0,1,7,289,33,30,0,2,1
5,0,0,0,1,10,179,38,31,0,0,0
6,0,0,0,1,7,361,28,27,0,1,4
7,0,0,0,1,7,260,36,23,0,4,0
8,0,0,1,0,6,155,34,25,0,2,0
9,0,0,0,1,7,235,37,29,1,1,1
10,1,0,0,0,7,260,36,23,0,4,0
11,1,0,0,0,7,260,36,23,0,4,0
12,1,0,0,0,7,260,36,23,0,4,0
13,1,0,0,0,7,179,38,31,0,0,0
14,0,0,0,1,7,179,38,31,0,0,0
15,1,0,0,0,7,246,41,23,0,0,0
16,0,0,0,1,7,179,38,31,0,0,0
17,0,0,1,0,7,179,38,31,0,0,0
18,1,0,0,0,7,189,33,25,0,2,2
19,0,0,0,1,5,248,47,32,0,2,1
20,1,0,0,0,12,330,28,25,1,0,0
21,1,0,0,0,3,179,38,31,0,0,0
22,1,0,0,0,10,361,28,27,0,1,4
23,0,0,0,1,8,260,36,23,0,4,0
24,0,0,1,0,8,289,33,30,0,2,1
25,0,0,0,1,8,361,28,27,0,1,4
26,0,0,0,1,4,289,33,30,0,2,1
27,0,0,0,1,12,157,29,22,0,0,0
28,0,0,1,0,8,289,33,30,0,2,1
29,0,0,0,1,8,179,38,31,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,1,4,155,34,25,0,2,0
671,0,0,1,0,4,225,28,24,0,1,2
672,1,0,0,0,4,118,50,31,0,1,0
673,0,0,0,1,4,179,30,19,1,0,0
674,0,0,0,1,7,235,37,29,1,1,1
675,0,0,1,0,9,225,41,28,1,2,2
676,0,0,0,1,9,235,32,25,1,0,0
677,1,0,0,0,9,118,37,28,0,0,0
678,0,0,0,1,9,235,43,38,0,1,0
679,1,0,0,0,10,179,30,19,1,0,0
680,0,0,0,1,10,291,40,25,0,1,1
681,1,0,0,0,10,225,41,28,1,2,2
682,0,0,1,0,11,300,43,25,0,2,1
683,0,0,0,1,11,225,41,28,1,2,2
684,0,0,0,1,11,179,30,19,1,0,0
685,0,0,0,1,5,118,50,31,0,1,0
686,1,0,0,0,5,118,50,31,0,1,0
687,0,0,0,1,5,118,37,28,0,0,0
688,0,0,0,0,5,118,50,31,0,1,0
689,0,0,0,1,5,179,30,19,1,0,0
690,0,0,0,0,5,378,36,21,0,2,4
691,0,1,0,0,5,179,40,22,1,2,0
692,1,0,0,0,5,155,34,25,0,2,0
693,1,0,0,0,5,235,32,25,1,0,0
694,0,0,0,1,5,291,40,25,0,1,1
695,1,0,0,0,5,179,40,22,1,2,0
696,1,0,0,0,5,225,28,24,0,1,2
697,1,0,0,0,5,330,28,25,1,0,0
698,0,0,0,1,5,235,32,25,1,0,0
699,0,0,0,1,5,291,40,25,0,1,1

In [79]:
unscaled_inputs = data_with_targets.iloc[:,:11]

## Standardize the data

In [80]:
#from sklearn.preprocessing import StandardScaler

#absenteeism_scaler = StandardScaler()

In [81]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator,TransformerMixin):
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        self.scaler = StandardScaler(copy,with_mean,with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    def fit(self,X, y = None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    def transform(self, X , y = None, copy = None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns = self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis = 1)[init_col_order]

In [82]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [83]:
#columns_to_scale =['Month Value',
 ##     'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
   #    'Children', 'Pet']

columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

In [84]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [85]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [86]:
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pet'],
             copy=None, with_mean=None, with_std=None)

In [87]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [88]:
scaled_inputs

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pet
0,0,0,0,1,0.030796,1.005844,-0.536062,0.767431,0,0.880469,0.268487
1,0,0,0,0,0.030796,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
2,0,0,0,1,0.030796,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
3,1,0,0,0,0.030796,0.854936,0.405184,-0.643782,0,0.880469,-0.589690
4,0,0,0,1,0.030796,1.005844,-0.536062,0.767431,0,0.880469,0.268487
5,0,0,0,1,0.929019,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
6,0,0,0,1,0.030796,2.092381,-1.320435,0.061825,0,-0.019280,2.843016
7,0,0,0,1,0.030796,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690
8,0,0,1,0,-0.268611,-1.016322,-0.379188,-0.408580,0,0.880469,-0.589690
9,0,0,0,1,0.030796,0.190942,0.091435,0.532229,1,-0.019280,0.268487
10,1,0,0,0,0.030796,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690
11,1,0,0,0,0.030796,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690
12,1,0,0,0,0.030796,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690
13,1,0,0,0,0.030796,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
14,0,0,0,1,0.030796,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
15,1,0,0,0,0.030796,0.356940,0.718933,-0.878984,0,-0.919030,-0.589690
16,0,0,0,1,0.030796,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
17,0,0,1,0,0.030796,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
18,1,0,0,0,0.030796,-0.503235,-0.536062,-0.408580,0,0.880469,1.126663
19,0,0,0,1,-0.568019,0.387122,1.660180,1.237836,0,0.880469,0.268487
20,1,0,0,0,1.527833,1.624567,-1.320435,-0.408580,1,-0.919030,-0.589690
21,1,0,0,0,-1.166834,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
22,1,0,0,0,0.929019,2.092381,-1.320435,0.061825,0,-0.019280,2.843016
23,0,0,0,1,0.330204,0.568211,-0.065439,-0.878984,0,2.679969,-0.589690
24,0,0,1,0,0.330204,1.005844,-0.536062,0.767431,0,0.880469,0.268487
25,0,0,0,1,0.330204,2.092381,-1.320435,0.061825,0,-0.019280,2.843016
26,0,0,0,1,-0.867426,1.005844,-0.536062,0.767431,0,0.880469,0.268487
27,0,0,0,1,1.527833,-0.986140,-1.163560,-1.114186,0,-0.919030,-0.589690
28,0,0,1,0,0.330204,1.005844,-0.536062,0.767431,0,0.880469,0.268487
29,0,0,0,1,0.330204,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690
...,...,...,...,...,...,...,...,...,...,...,...
670,0,0,0,1,-0.867426,-1.016322,-0.379188,-0.408580,0,0.880469,-0.589690
671,0,0,1,0,-0.867426,0.040034,-1.320435,-0.643782,0,-0.019280,1.126663
672,1,0,0,0,-0.867426,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
673,0,0,0,1,-0.867426,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690
674,0,0,0,1,0.030796,0.190942,0.091435,0.532229,1,-0.019280,0.268487
675,0,0,1,0,0.629611,0.040034,0.718933,0.297027,1,0.880469,1.126663
676,0,0,0,1,0.629611,0.190942,-0.692937,-0.408580,1,-0.919030,-0.589690
677,1,0,0,0,0.629611,-1.574681,0.091435,0.297027,0,-0.919030,-0.589690
678,0,0,0,1,0.629611,0.190942,1.032682,2.649049,0,-0.019280,-0.589690
679,1,0,0,0,0.929019,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690
680,0,0,0,1,0.929019,1.036026,0.562059,-0.408580,0,-0.019280,0.268487
681,1,0,0,0,0.929019,0.040034,0.718933,0.297027,1,0.880469,1.126663
682,0,0,1,0,1.228426,1.171843,1.032682,-0.408580,0,0.880469,0.268487
683,0,0,0,1,1.228426,0.040034,0.718933,0.297027,1,0.880469,1.126663
684,0,0,0,1,1.228426,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690
685,0,0,0,1,-0.568019,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
686,1,0,0,0,-0.568019,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
687,0,0,0,1,-0.568019,-1.574681,0.091435,0.297027,0,-0.919030,-0.589690
688,0,0,0,0,-0.568019,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
689,0,0,0,1,-0.568019,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690
690,0,0,0,0,-0.568019,2.348925,-0.065439,-1.349389,0,0.880469,2.843016
691,0,1,0,0,-0.568019,-0.654143,0.562059,-1.114186,1,0.880469,-0.589690
692,1,0,0,0,-0.568019,-1.016322,-0.379188,-0.408580,0,0.880469,-0.589690
693,1,0,0,0,-0.568019,0.190942,-0.692937,-0.408580,1,-0.919030,-0.589690
694,0,0,0,1,-0.568019,1.036026,0.562059,-0.408580,0,-0.019280,0.268487
695,1,0,0,0,-0.568019,-0.654143,0.562059,-1.114186,1,0.880469,-0.589690
696,1,0,0,0,-0.568019,0.040034,-1.320435,-0.643782,0,-0.019280,1.126663
697,1,0,0,0,-0.568019,1.624567,-1.320435,-0.408580,1,-0.919030,-0.589690
698,0,0,0,1,-0.568019,0.190942,-0.692937,-0.408580,1,-0.919030,-0.589690
699,0,0,0,1,-0.568019,1.036026,0.562059,-0.408580,0,-0.019280,0.268487

In [89]:
scaled_inputs.shape

(700, 11)

## Split the data into train & test and shuffle

### Import the relevant module

In [90]:
from sklearn.model_selection import train_test_split

### Split

In [91]:
train_test_split(scaled_inputs, targets )

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
 515         0         0         0         1     0.929019
 526         1         0         0         0     0.929019
 224         1         0         0         0    -0.268611
 520         0         0         0         1     0.929019
 51          0         0         0         0     0.629611
 494         0         0         0         1     0.330204
 548         0         0         0         0     1.228426
 567         0         0         0         1     1.527833
 657         0         0         1         0    -0.867426
 465         0         0         0         1     0.030796
 466         0         0         0         1     0.030796
 194         1         0         0         0     0.330204
 480         0         0         0         1    -1.166834
 158         0         1         0         0    -1.166834
 123         0         0         0         1     1.527833
 429         0         0         0         1     0.929019
 618         0         0         0         1    -0.568019
 682         0         0         1         0     1.228426
 685         0         0         0         1    -0.568019
 639         0         0         0         1    -1.166834
 141         0         0         0         1     1.228426
 393         0         0         0         1     0.929019
 341         0         0         0         1    -0.568019
 245         0         0         0         1     0.030796
 21          1         0         0         0    -1.166834
 87          1         0         0         0     1.228426
 552         0         0         0         1     1.228426
 11          1         0         0         0     0.030796
 450         0         0         0         1    -0.268611
 628         0         0         0         1     1.527833
 ..        ...       ...       ...       ...          ...
 150         0         0         0         1    -1.466241
 529         1         0         0         0     0.929019
 100         0         0         0         1    -1.466241
 452         0         0         0         1    -0.268611
 392         0         0         0         1     0.929019
 444         0         0         0         1     0.330204
 317         1         0         0         0     0.030796
 668         0         1         0         0    -0.867426
 609         0         0         0         1    -1.466241
 453         0         0         0         1    -0.268611
 490         0         0         0         1     0.330204
 629         0         0         1         0     1.527833
 153         0         0         0         1    -1.466241
 554         0         0         0         1     1.228426
 440         0         0         0         1    -0.568019
 172         1         0         0         0    -1.166834
 209         1         0         0         0     1.228426
 197         0         0         1         0    -0.867426
 645         0         0         0         1    -1.166834
 173         1         0         0         0    -1.166834
 85          1         0         0         0    -1.466241
 411         0         0         0         1    -1.166834
 366         0         0         0         1    -1.765648
 188         0         0         0         1    -0.867426
 458         1         0         0         0    -0.268611
 98          0         0         0         1    -1.765648
 641         0         0         0         1    -1.166834
 596         1         0         0         0    -1.466241
 30          0         0         1         0     0.330204
 289         0         0         0         1    -0.568019

      Transportation Expense       Age  Body Mass Index  Education  Children  \
 515                0.040034 -1.320435        -0.643782          0 -0.019280
 526                0.040034 -1.320435        -0.643782          0 -0.019280
 224                0.356940  0.718933        -0.878984          0 -0.919030
 520               -0.654143  0.248310         1.002633          0 -0.919030
 51                 0.040034 -1.320435        -0.643782          0 -0.019280
 494                0.568211 -0.065439        -0.878984          0  2.679969
 548                1.036026  0.562059        -0.408580          0 -0.019280
 567                0.040034 -1.320435        -0.643782          0 -0.019280
 657                0.387122  1.660180         1.237836          0  0.880469
 465               -1.574681  0.091435         0.297027          0 -0.919030
 466                0.568211 -0.065439        -0.878984          0  2.679969
 194                0.356940  0.718933        -0.878984          0 -0.919030
 480               -0.654143  0.248310         1.002633          0 -0.919030
 158               -0.654143  0.562059        -1.114186          1  0.880469
 123               -1.574681  0.091435         0.297027          0 -0.919030
 429               -0.654143  0.248310         1.002633          0 -0.919030
 618               -0.654143  0.248310         1.002633          0 -0.919030
 682                1.171843  1.032682        -0.408580          0  0.880469
 685               -1.574681  2.130803         1.002633          0 -0.019280
 639                1.005844 -0.536062         0.767431          0  0.880469
 141               -0.503235 -0.536062        -0.408580          0  0.880469
 393                0.568211 -0.065439        -0.878984          0  2.679969
 341               -0.654143  0.248310         1.002633          0 -0.919030
 245               -0.986140 -1.163560        -1.114186          0 -0.919030
 21                -0.654143  0.248310         1.002633          0 -0.919030
 87                 1.036026  0.562059        -0.408580          0 -0.019280
 552                0.040034 -1.320435        -0.643782          0 -0.019280
 11                 0.568211 -0.065439        -0.878984          0  2.679969
 450               -0.654143  0.248310         1.002633          0 -0.919030
 628                0.190942 -0.692937        -0.408580          1 -0.919030
 ..                      ...       ...              ...        ...       ...
 150                0.040034 -1.320435        -0.643782          0 -0.019280
 529                0.387122  1.660180         1.237836          0  0.880469
 100               -1.574681  2.130803         1.002633          0 -0.019280
 452               -0.654143  0.248310         1.002633          0 -0.919030
 392                0.356940  0.718933        -0.878984          0 -0.919030
 444                0.040034 -1.320435        -0.643782          0 -0.019280
 317               -1.574681  0.091435         0.297027          0 -0.919030
 668                0.190942 -0.692937        -0.408580          1 -0.919030
 609                0.190942 -0.692937        -0.408580          1 -0.919030
 453                0.040034 -1.320435        -0.643782          0 -0.019280
 490                0.190942  0.091435         0.532229          1 -0.019280
 629                2.092381 -1.320435         0.061825          0 -0.019280
 153                0.040034 -1.320435        -0.643782          0 -0.019280
 554                2.092381 -1.320435         0.061825          0 -0.019280
 440               -0.654143 -1.006686        -1.819793          1 -0.919030
 172                0.854936  0.405184        -0.643782          0  0.880469
 209               -0.578689 -1.477309        -1.349389          0 -0.919030
 197                0.568211 -0.065439        -0.878984          0  2.679969
 645               -0.654143  0.248310         1.002633          0 -0.919030
 173               -0.654143  0.248310         1.002633          0 -0.919030
 85                -1.016322 -0.379188        -0.408580          0  0.880469
 411                0.356940  0.718933        -0.878984          0 -0.919030
 366               -1.574681  2.130803         1.002633          0 -0.019280
 188               -1.016322 -0.379188        -0.408580          0  0.880469
 458                1.624567 -1.320435        -0.408580          1 -0.919030
 98                 0.387122  1.660180         1.237836          0  0.880469
 641               -0.654143  0.248310         1.002633          0 -0.919030
 596                0.040034 -1.320435        -0.643782          0 -0.019280
 30                -0.654143  0.248310         1.002633          0 -0.919030
 289                1.005844 -0.536062         0.767431          0  0.880469

           Pet
 515  1.126663
 526  1.126663
 224 -0.589690
 520 -0.589690
 51   1.126663
 494 -0.589690
 548  0.268487
 567  1.126663
 657  0.268487
 465 -0.589690
 466 -0.589690
 194 -0.589690
 480 -0.589690
 158 -0.589690
 123 -0.589690
 429 -0.589690
 618 -0.589690
 682  0.268487
 685 -0.589690
 639  0.268487
 141  1.126663
 393 -0.589690
 341 -0.589690
 245 -0.589690
 21  -0.589690
 87   0.268487
 552  1.126663
 11  -0.589690
 450 -0.589690
 628 -0.589690
 ..        ...
 150  1.126663
 529  0.268487
 100 -0.589690
 452 -0.589690
 392 -0.589690
 444  1.126663
 317 -0.589690
 668 -0.589690
 609 -0.589690
 453  1.126663
 490  0.268487
 629  2.843016
 153  1.126663
 554  2.843016
 440 -0.589690
 172 -0.589690
 209 -0.589690
 197 -0.589690
 645 -0.589690
 173 -0.589690
 85  -0.589690
 411 -0.589690
 366 -0.589690
 188 -0.589690
 458 -0.589690
 98   0.268487
 641 -0.589690
 596  1.126663
 30  -0.589690
 289  0.268487

 [525 rows x 11 columns],
      Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
 57          0         0         0         1     0.629611
 203         0         0         0         0    -0.867426
 199         1         0         0         0    -0.867426
 347         0         0         0         1     1.527833
 431         0         0         0         1     1.527833
 654         1         0         0         0    -1.466241
 315         1         0         0         0     0.929019
 475         0         0         0         1     0.030796
 642         0         0         0         1    -1.166834
 479         0         0         0         1     0.030796
 3           1         0         0         0     0.030796
 399         0         0         0         1    -1.166834
 437         0         0         0         1    -0.568019
 10          1         0         0         0     0.030796
 498         0         0         0         1    -0.568019
 407         0         0         0         0    -1.166834
 307         0         0         0         1     0.929019
 448         0         0         0         1     1.527833
 143         0         0         0         1     1.527833
 459         1         0         0         0    -0.268611
 216         0         0         0         0    -0.568019
 97          0         0         0         1     1.228426
 256         1         0         0         0     0.929019
 329         0         0         0         1     1.228426
 517         0         0         0         1     0.929019
 168         1         0         0         0    -1.166834
 335         0         1         0         0     1.228426
 107         0         0         0         1     1.228426
 48          0         0         0         1    -0.867426
 631         0         0         0         1    -1.166834
 ..        ...       ...       ...       ...          ...
 488         0         0         0         1     0.330204
 425         1         0         0         0    -1.765648
 233         1         0         0         0     0.929019
 646         0         0         0         1    -1.166834
 576         1         0         0         0     1.228426
 265         0         0         0         1     0.330204
 325         0         0         0         0     1.228426
 675         0         0         1         0     0.629611
 627         0         0         0         1     0.629611
 678         0         0         0         1     0.629611
 438         0         0         0         1    -0.568019
 404         1         0         0         0    -1.166834
 558         1         0         0         0     0.330204
 243         1         0         0         0     0.030796
 1           0         0         0         0     0.030796
 31          0         0         1         0     0.330204
 358         0         0         0         1    -0.867426
 549         0         0         0         0     1.228426
 591         0         0         0         1     0.330204
 139         1         0         0         0     0.929019
 63          0         0         0         1     0.929019
 632         0         0         0         1    -1.166834
 324         0         0         0         1     1.228426
 72          0         0         0         1     0.929019
 420         1         0         0         0    -0.867426
 68          0         0         0         1    -0.268611
 507         1         0         0         0    -0.568019
 110         0         0         0         1     1.228426
 193         0         0         0         1     0.330204
 226         0         0         0         1    -0.268611

      Transportation Expense       Age  Body Mass Index  Education  Children  \
 57                -0.654143  0.248310         1.002633          0 -0.919030
 203                0.190942  1.817054         1.473038          0 -0.019280
 199               -1.016322 -0.379188        -0.408580          0  0.880469
 347               -0.654143  0.248310         1.002633          0 -0.919030
 431                0.568211 -0.065439        -0.878984          0  2.679969
 654                0.040034 -1.320435        -0.643782          0 -0.019280
 315               -0.654143 -1.006686        -1.819793          1 -0.919030
 475                1.005844 -0.536062         0.767431          0  0.880469
 642                0.387122  1.660180         1.237836          0  0.880469
 479                0.854936  0.405184        -0.643782          0  0.880469
 3                  0.854936  0.405184        -0.643782          0  0.880469
 399                2.092381 -1.320435         0.061825          0 -0.019280
 437               -0.654143 -1.006686        -1.819793          1 -0.919030
 10                 0.568211 -0.065439        -0.878984          0  2.679969
 498               -1.016322 -0.379188        -0.408580          0  0.880469
 407               -1.574681  2.130803         1.002633          0 -0.019280
 307                1.036026  0.562059        -0.408580          0 -0.019280
 448               -0.654143  0.248310         1.002633          0 -0.919030
 143                1.005844 -0.536062         0.767431          0  0.880469
 459                0.190942  0.091435         0.532229          1 -0.019280
 216                2.499833  2.130803        -0.643782          0 -0.919030
 97                 1.036026  0.562059        -0.408580          0 -0.019280
 256                1.171843  1.032682        -0.408580          0  0.880469
 329               -0.654143  0.248310         1.002633          0 -0.919030
 517                2.213108 -0.849811        -0.408580          0  1.780219
 168                1.005844 -0.536062         0.767431          0  0.880469
 335                0.568211 -0.065439        -0.878984          0  2.679969
 107                0.568211 -0.065439        -0.878984          0  2.679969
 48                 0.568211 -0.065439        -0.878984          0  2.679969
 631               -0.654143  0.248310         1.002633          0 -0.919030
 ..                      ...       ...              ...        ...       ...
 488               -0.654143  0.562059        -1.114186          1  0.880469
 425                0.190942  1.032682         2.649049          0 -0.019280
 233               -0.654143  0.248310         1.002633          0 -0.919030
 646               -0.654143  0.248310         1.002633          0 -0.919030
 576                1.005844  1.973929         2.178644          0 -0.919030
 265                0.190942  0.091435         0.532229          1 -0.019280
 325                1.624567 -1.320435        -0.408580          1 -0.919030
 675                0.040034  0.718933         0.297027          1  0.880469
 627               -0.654143 -1.006686        -1.819793          1 -0.919030
 678                0.190942  1.032682         2.649049          0 -0.019280
 438               -1.574681  0.091435         0.297027          0 -0.919030
 404               -1.574681  2.130803         1.002633          0 -0.019280
 558               -0.654143 -1.006686        -1.819793          1 -0.919030
 243                1.624567 -1.320435        -0.408580          1 -0.919030
 1                 -1.574681  2.130803         1.002633          0 -0.019280
 31                 0.190942  1.817054         1.473038          0 -0.019280
 358                0.040034 -1.320435        -0.643782          0 -0.019280
 549                1.005844 -0.536062         0.767431          0  0.880469
 591               -0.654143 -1.006686        -1.819793          1 -0.919030
 139               -0.654143  0.248310         1.002633          0 -0.919030
 63                -1.574681  0.091435         0.297027          0 -0.919030
 632               -0.654143  0.248310         1.002633          0 -0.919030
 324                0.190942  1.032682         2.649049          0 -0.019280
 72                -0.654143  0.248310         1.002633          0 -0.919030
 420               -1.574681  2.130803         1.002633          0 -0.019280
 68                -1.574681  0.091435         0.297027          0 -0.919030
 507                1.005844  1.973929         2.178644          0 -0.919030
 110               -1.574681  0.091435         0.297027          0 -0.919030
 193                1.036026  0.562059        -0.408580          0 -0.019280
 226               -1.016322 -0.379188        -0.408580          0  0.880469

           Pet
 57  -0.589690
 203  3.701192
 199 -0.589690
 347 -0.589690
 431 -0.589690
 654  1.126663
 315 -0.589690
 475  0.268487
 642  0.268487
 479 -0.589690
 3   -0.589690
 399  2.843016
 437 -0.589690
 10  -0.589690
 498 -0.589690
 407 -0.589690
 307  0.268487
 448 -0.589690
 143  0.268487
 459  0.268487
 216 -0.589690
 97   0.268487
 256  0.268487
 329 -0.589690
 517 -0.589690
 168  0.268487
 335 -0.589690
 107 -0.589690
 48  -0.589690
 631 -0.589690
 ..        ...
 488 -0.589690
 425 -0.589690
 233 -0.589690
 646 -0.589690
 576  1.126663
 265  0.268487
 325 -0.589690
 675  1.126663
 627 -0.589690
 678 -0.589690
 438 -0.589690
 404 -0.589690
 558 -0.589690
 243 -0.589690
 1   -0.589690
 31   3.701192
 358  1.126663
 549  0.268487
 591 -0.589690
 139 -0.589690
 63  -0.589690
 632 -0.589690
 324 -0.589690
 72  -0.589690
 420 -0.589690
 68  -0.589690
 507  1.126663
 110 -0.589690
 193  0.268487
 226 -0.589690

 [175 rows x 11 columns],
 array([0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
        0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
        0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
        1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
        1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
        0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
        0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
        0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
        1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
        0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
        1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
        0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
        1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
        1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
        1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
        1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
        0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,

In [92]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, #train_size = 0.8, 
                                                                            test_size = 0.2, random_state = 20)

In [93]:
print(x_train.shape, y_train.shape)

(560, 11) (560,)

In [94]:
print(x_test.shape, y_test.shape)

(140, 11) (140,)

## Logistic regression with Sklearn

In [96]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

## Training the model

In [97]:
reg = LogisticRegression()

In [98]:
reg.fit(x_train,y_train)

C:\Users\tatla\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [99]:
reg.score(x_train,y_train)

0.775

## Manually check the accuracy

In [100]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0])

In [101]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0])

In [103]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True, False,
       False, False,  True,  True, False,  True,  True,  True,  True,
        True, False,  True, False,  True, False,  True, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True, False,
        True, False, False,  True,  True,  True,  True,  True, False,
       False, False,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False, False,
       False,  True,  True,  True,  True, False,  True, False,  True,
       False,  True,  True,  True,  True,  True, False,  True, False,
       False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True, False, False,  True,  True,  True, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True, False,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True, False,  True,  True, False,
        True,  True,  True, False,  True,  True, False,  True, False,
        True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True, False, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False, False,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
       False, False, False,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
       False,  True])

In [104]:
np.sum((model_outputs == y_train))

434

In [105]:
model_outputs.shape[0]

560

In [106]:
np.sum((model_outputs == y_train)) / model_outputs.shape[0]

0.775

 ## Finding the intercept and coeffcients

In [107]:
reg.intercept_

array([-1.43138127])

In [108]:
reg.coef_

array([[ 2.60237227,  0.84350002,  2.94078723,  0.63723433,  0.00565051,
         0.61953401, -0.17635497,  0.28410321, -0.26372527,  0.35195032,
        -0.27369766]])

In [109]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [110]:
feature_name = unscaled_inputs.columns.values

In [111]:
summary_table = pd.DataFrame(columns=['Feature name'], data = feature_name)

summary_table['Cofficient'] = np.transpose(reg.coef_)

summary_table

              Feature name  Cofficient
0                 Reason_1    2.602372
1                 Reason_2    0.843500
2                 Reason_3    2.940787
3                 Reason_4    0.637234
4              Month Value    0.005651
5   Transportation Expense    0.619534
6                      Age   -0.176355
7          Body Mass Index    0.284103
8                Education   -0.263725
9                 Children    0.351950
10                     Pet   -0.273698

In [112]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

              Feature name  Cofficient
0                Intercept   -1.431381
1                 Reason_1    2.602372
2                 Reason_2    0.843500
3                 Reason_3    2.940787
4                 Reason_4    0.637234
5              Month Value    0.005651
6   Transportation Expense    0.619534
7                      Age   -0.176355
8          Body Mass Index    0.284103
9                Education   -0.263725
10                Children    0.351950
11                     Pet   -0.273698

## Interpreting the coefficients

In [113]:
summary_table['Odds_ratio'] = np.exp(summary_table.Cofficient)
summary_table

              Feature name  Cofficient  Odds_ratio
0                Intercept   -1.431381    0.238979
1                 Reason_1    2.602372   13.495716
2                 Reason_2    0.843500    2.324489
3                 Reason_3    2.940787   18.930743
4                 Reason_4    0.637234    1.891243
5              Month Value    0.005651    1.005667
6   Transportation Expense    0.619534    1.858062
7                      Age   -0.176355    0.838320
8          Body Mass Index    0.284103    1.328570
9                Education   -0.263725    0.768185
10                Children    0.351950    1.421838
11                     Pet   -0.273698    0.760562

In [114]:
summary_table.sort_values('Odds_ratio', ascending = False)

              Feature name  Cofficient  Odds_ratio
3                 Reason_3    2.940787   18.930743
1                 Reason_1    2.602372   13.495716
2                 Reason_2    0.843500    2.324489
4                 Reason_4    0.637234    1.891243
6   Transportation Expense    0.619534    1.858062
10                Children    0.351950    1.421838
8          Body Mass Index    0.284103    1.328570
5              Month Value    0.005651    1.005667
7                      Age   -0.176355    0.838320
9                Education   -0.263725    0.768185
11                     Pet   -0.273698    0.760562
0                Intercept   -1.431381    0.238979

## Test the model

In [115]:
reg.score(x_test,y_test)

0.7357142857142858

In [116]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.75308922, 0.24691078],
       [0.60926091, 0.39073909],
       [0.4859575 , 0.5140425 ],
       [0.7552847 , 0.2447153 ],
       [0.0839675 , 0.9160325 ],
       [0.30192695, 0.69807305],
       [0.30166774, 0.69833226],
       [0.1151045 , 0.8848955 ],
       [0.73775967, 0.26224033],
       [0.75403176, 0.24596824],
       [0.50719215, 0.49280785],
       [0.19719276, 0.80280724],
       [0.06163196, 0.93836804],
       [0.70917025, 0.29082975],
       [0.29280547, 0.70719453],
       [0.5241047 , 0.4758953 ],
       [0.50676929, 0.49323071],
       [0.50888352, 0.49111648],
       [0.367008  , 0.632992  ],
       [0.06355661, 0.93644339],
       [0.73644831, 0.26355169],
       [0.7552847 , 0.2447153 ],
       [0.47457156, 0.52542844],
       [0.47288443, 0.52711557],
       [0.22026535, 0.77973465],
       [0.73808685, 0.26191315],
       [0.51184512, 0.48815488],
       [0.87683579, 0.12316421],
       [0.23445563, 0.76554437],
       [0.7552847 , 0.2447153 ],
       [0.61087074, 0.38912926],
       [0.28414073, 0.71585927],
       [0.29943679, 0.70056321],
       [0.50634641, 0.49365359],
       [0.7552847 , 0.2447153 ],
       [0.40453482, 0.59546518],
       [0.73743223, 0.26256777],
       [0.21439711, 0.78560289],
       [0.56310493, 0.43689507],
       [0.39544424, 0.60455576],
       [0.75559726, 0.24440274],
       [0.50110763, 0.49889237],
       [0.73874043, 0.26125957],
       [0.55298784, 0.44701216],
       [0.19310398, 0.80689602],
       [0.39168937, 0.60831063],
       [0.27751475, 0.72248525],
       [0.75465877, 0.24534123],
       [0.75144366, 0.24855634],
       [0.75590955, 0.24409045],
       [0.49772404, 0.50227596],
       [0.67413797, 0.32586203],
       [0.30192695, 0.69807305],
       [0.75302024, 0.24697976],
       [0.17932441, 0.82067559],
       [0.60845511, 0.39154489],
       [0.09280493, 0.90719507],
       [0.73302148, 0.26697852],
       [0.64208684, 0.35791316],
       [0.64169795, 0.35830205],
       [0.29600002, 0.70399998],
       [0.3008583 , 0.6991417 ],
       [0.73202705, 0.26797295],
       [0.21881596, 0.78118404],
       [0.75380354, 0.24619646],
       [0.75340367, 0.24659633],
       [0.90974125, 0.09025875],
       [0.73710452, 0.26289548],
       [0.2325724 , 0.7674276 ],
       [0.70777255, 0.29222745],
       [0.73939295, 0.26060705],
       [0.64716344, 0.35283656],
       [0.11680764, 0.88319236],
       [0.56393718, 0.43606282],
       [0.406166  , 0.593834  ],
       [0.7552847 , 0.2447153 ],
       [0.23415211, 0.76584789],
       [0.25308247, 0.74691753],
       [0.29723426, 0.70276574],
       [0.36543731, 0.63456269],
       [0.73841377, 0.26158623],
       [0.9123835 , 0.0876165 ],
       [0.73003114, 0.26996886],
       [0.28139582, 0.71860418],
       [0.53366197, 0.46633803],
       [0.87738286, 0.12261714],
       [0.30050256, 0.69949744],
       [0.47288443, 0.52711557],
       [0.7464465 , 0.2535535 ],
       [0.28414073, 0.71585927],
       [0.80468048, 0.19531952],
       [0.86529144, 0.13470856],
       [0.75245951, 0.24754049],
       [0.7527745 , 0.2472255 ],
       [0.75403176, 0.24596824],
       [0.12887064, 0.87112936],
       [0.75245951, 0.24754049],
       [0.27480928, 0.72519072],
       [0.75270546, 0.24729454],
       [0.80308014, 0.19691986],
       [0.40535014, 0.59464986],
       [0.28414073, 0.71585927],
       [0.29900425, 0.70099575],
       [0.29424034, 0.70575966],
       [0.5635211 , 0.4364789 ],
       [0.56643175, 0.43356825],
       [0.75308922, 0.24691078],
       [0.12887064, 0.87112936],
       [0.23944262, 0.76055738],
       [0.86548852, 0.13451148],
       [0.91265361, 0.08734639],
       [0.08800759, 0.91199241],
       [0.34705733, 0.65294267],
       [0.61207652, 0.38792348],
       [0.40575801, 0.59424199],
       [0.3970632 , 0.6029368 ],
       [0.21411229, 0.78588771],
       [0.15452766, 0.84547234],
       [0.43678858, 0.56321142],
       [0.73677655, 0.26322345],
       [0.75371785, 0.24628215],
       [0.8761031 , 0.1238969 ],
       [0.19746072, 0.80253928],
       [0.50237647, 0.49762353],
       [0.75403176, 0.24596824],
       [0.70847189, 0.29152811],
       [0.75559726, 0.24440274],
       [0.86489655, 0.13510345],
       [0.30014706, 0.69985294],
       [0.73644831, 0.26355169],
       [0.39503985, 0.60496015],
       [0.75559726, 0.24440274],
       [0.75465877, 0.24534123],
       [0.7060199 , 0.2939801 ],
       [0.73169505, 0.26830495],
       [0.40902552, 0.59097448],
       [0.50634641, 0.49365359],
       [0.70742251, 0.29257749],
       [0.75270546, 0.24729454],
       [0.56268867, 0.43731133]])

In [117]:
predicted_proba.shape

(140, 2)

In [118]:
predicted_proba[:,1]

array([0.24691078, 0.39073909, 0.5140425 , 0.2447153 , 0.9160325 ,
       0.69807305, 0.69833226, 0.8848955 , 0.26224033, 0.24596824,
       0.49280785, 0.80280724, 0.93836804, 0.29082975, 0.70719453,
       0.4758953 , 0.49323071, 0.49111648, 0.632992  , 0.93644339,
       0.26355169, 0.2447153 , 0.52542844, 0.52711557, 0.77973465,
       0.26191315, 0.48815488, 0.12316421, 0.76554437, 0.2447153 ,
       0.38912926, 0.71585927, 0.70056321, 0.49365359, 0.2447153 ,
       0.59546518, 0.26256777, 0.78560289, 0.43689507, 0.60455576,
       0.24440274, 0.49889237, 0.26125957, 0.44701216, 0.80689602,
       0.60831063, 0.72248525, 0.24534123, 0.24855634, 0.24409045,
       0.50227596, 0.32586203, 0.69807305, 0.24697976, 0.82067559,
       0.39154489, 0.90719507, 0.26697852, 0.35791316, 0.35830205,
       0.70399998, 0.6991417 , 0.26797295, 0.78118404, 0.24619646,
       0.24659633, 0.09025875, 0.26289548, 0.7674276 , 0.29222745,
       0.26060705, 0.35283656, 0.88319236, 0.43606282, 0.593834  ,
       0.2447153 , 0.76584789, 0.74691753, 0.70276574, 0.63456269,
       0.26158623, 0.0876165 , 0.26996886, 0.71860418, 0.46633803,
       0.12261714, 0.69949744, 0.52711557, 0.2535535 , 0.71585927,
       0.19531952, 0.13470856, 0.24754049, 0.2472255 , 0.24596824,
       0.87112936, 0.24754049, 0.72519072, 0.24729454, 0.19691986,
       0.59464986, 0.71585927, 0.70099575, 0.70575966, 0.4364789 ,
       0.43356825, 0.24691078, 0.87112936, 0.76055738, 0.13451148,
       0.08734639, 0.91199241, 0.65294267, 0.38792348, 0.59424199,
       0.6029368 , 0.78588771, 0.84547234, 0.56321142, 0.26322345,
       0.24628215, 0.1238969 , 0.80253928, 0.49762353, 0.24596824,
       0.29152811, 0.24440274, 0.13510345, 0.69985294, 0.26355169,
       0.60496015, 0.24440274, 0.24534123, 0.2939801 , 0.26830495,
       0.59097448, 0.49365359, 0.29257749, 0.24729454, 0.43731133])

## Save the model

In [119]:
import pickle

In [120]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [121]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)